pipeline {
    agent any
    tools {
        maven "maven-nodo-principal"
    }

    stages {
        stage('Build') {
            steps {
                dir ('maven-adderapp') {
                  sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir ('maven-adderapp') {
                    sh "mvn test"
                }
            }
        }
        stage('Deploy') {
            steps {

                echo 'Deploying....'
            }
        }
    }

    post {
        always {
            dir('maven-adderapp') {
                junit 'target/surefire-reports/*.xml'
            }
        }
        success {
            dir ('maven-adderapp') {
                script {
                    pom = readMavenPom file: "pom.xml";

                    nexusArtifactUploader(
                        nexusVersion: "3.33.1-01",
                        protocol: "http",
                        nexusUrl: "10.0.0.2",
                        groupId: pom.groupId,
                        version: pom.version,
                        repository: "maven-jenkins",
                        credentialsId: "nexus",
                        artifacts: [
                            [artifactId: pom.artifactId,
                            classifier: '',
                            file: artifactPath,
                            type: pom.packaging],
                            [artifactId: pom.artifactId,
                            classifier: '',
                            file: "pom.xml",
                            type: "pom"]
                        ]
                    );
                }
            }
        }
    }
}