pipeline {
    agent any
    tools {
        maven "maven-nodo-principal"
    }

    stages {
        stage('Build') {
            steps {
                dir ('maven-adderapp') {
                  sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir ('maven-adderapp') {
                    sh "mvn test"
                    junit 'surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }

    post {
        success {
            dir ('maven-adderapp') {
              archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
            //junit 'build/reports/**/*.xml'
        }
    }
}