# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
  config.vm.box = "ubuntu/bionic64"
  config.vm.boot_timeout = 900
  server.vm.hostname = "server"
  server.vm.network "public_network"
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y python
  apt-get install -y python-pip && pip install boto3
  apt-get install -y ansible
  apt-get install -y awscli
  SHELL
  end  
end
